# Generated by Django 4.2.11 on 2025-05-06 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("closet", "0006_rename_uploader_clothingitem_owner"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedOutfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="closet.outfit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
