# Generated by Django 5.1.7 on 2025-04-22 10:42

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
