# Generated by Django 5.1.7 on 2025-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
