# Generated by Django 5.1.7 on 2025-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0002_showroom_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
