# Generated by Django 5.1.7 on 2025-04-25 06:03

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_outfits', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='listed_items',
            field=models.ManyToManyField(blank=True, related_name='outfit_items', to='closet.clothingitem'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='comment',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.outfit'),
        ),
    ]
