# Generated by Django 5.1.7 on 2025-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('GREY', 'Grey'), ('WHITE', 'White'), ('BROWN', 'Brown'), ('CREAM', 'Cream'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('BURGUNDY', 'Burgundy'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('BLUE', 'Blue'), ('NAVY', 'Navy'), ('GREEN', 'Green'), ('KHAKI', 'Khaki'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('MULTI', 'Multicolor')], default='BLACK', max_length=10),
        ),
    ]
