# Generated by Django 5.1.7 on 2025-05-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='closet.clothingitem'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='user_management.profile'),
        ),
    ]
