# Generated by Django 5.1.7 on 2025-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_alter_clothingitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
