# Generated by Django 4.2.11 on 2025-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_alter_clothingitem_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="outfits", to="closet.clothingitem"
            ),
        ),
    ]
