# Generated by Django 5.1.7 on 2025-04-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_alter_comment_outfit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='owner',
            new_name='uploader',
        ),
    ]
