# Generated by Django 5.1.7 on 2025-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_outfit_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
