# Generated by Django 5.1.7 on 2025-04-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_rename_owner_clothingitem_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='uploader',
            new_name='owner',
        ),
    ]
