# Generated by Django 5.1.7 on 2025-04-18 10:29

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_clothingitem_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('user_management', '0004_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='items',
        ),
        migrations.AddField(
            model_name='outfit',
            name='caption',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_outfits', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='listed_items',
            field=models.ManyToManyField(blank=True, related_name='outfit_items', to='closet.clothingitem'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to='user_management.profile')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.outfit')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['date_created'],
            },
        ),
    ]
