# Generated by Django 5.1.7 on 2025-05-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_rename_uploader_clothingitem_owner'),
        ('user_management', '0002_profile_ootd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_clothing_items', to='user_management.profile'),
        ),
        migrations.CreateModel(
            name='ClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('closet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.clothingitem')),
            ],
            options={
                'verbose_name_plural': 'Closet Items',
                'ordering': ['date_added'],
                'unique_together': {('closet_owner', 'clothing_item')},
            },
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='clothing_items', through='closet.ClosetItem', to='user_management.profile'),
        ),
    ]
