# Generated by Django 5.1.7 on 2025-05-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0007_alter_clothingitem_owner_closetitem_and_more'),
        ('user_management', '0002_profile_ootd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='clothing_items_in_closet', through='closet.ClosetItem', to='user_management.profile'),
        ),
    ]
